### PR TITLE
Conform to new SPM syntax

### PR DESCRIPTION
**Pull request by nkleemann**
The format of `Package.swift` was deprecated since Swift 4.
Now this package can be installed with Xcode 11 by selecting "branch: master" in the install process.

Since I did not look into the tag/version problem I can give no update on that

### CODE REVIEW

**Comment by adamnemecek** [comment]
Do you want to clan this up? There's a lot of unrelated changes. I assume you only changed the package file.

**Comment by nkleemann** [comment]
I reverted all changes before sending the pull request. Only the Package.swift file should be changed now.

**Comment by adamnemecek** [comment]
It seems like you also removed the git ignore file.

**Comment by adamnemecek** [comment]
Can you just create a new pull request where you just change the package file. I can also update it from my end.

**Comment by nkleemann** [comment]
Done: #19 

Sorry, first time dealing with spm & pr's

**Comment by adamnemecek** [comment]
It's OK haha. Been there not too long ago.

**Comment by adamnemecek** [comment]
Fuck I didn't want to merge this.

**Pull request merged**
